spring.application.name=meetingroom

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MEETING_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.meetingroom.domain
mybatis.configuration.map-underscore-to-camel-case=true